### ISSUE TITLE
Assisticant with .NET Standard (1.4) support

### ISSUE THREAD

**Issue by 1iveowl** [michaellperry/Assisticant#25]
Any plans for Assisticant supporting .NET Standard?

**Comment by 1iveowl** [comment]
I've added a PR.

**Comment by 1iveowl** [comment]
Hmm. Looking deeper at this, what I really wanted to do was to use .NET Standard as a replacement for the PCL in a Xamarin Forms based project, which is now [becoming possible](https://blog.xamarin.com/building-xamarin-forms-apps-net-standard/).

 However, I now see that Assisticant is [not yet available for Xamarin Forms](https://groups.google.com/forum/#!msg/assisticant/qFJeixmIHMU/RyoChD6CCAAJ). Are there any plans for this? 

I suppose that PR #26 enables .NET Standard for native Xamarin apps, but obviously not for Xamarin Forms.

**Comment by michaellperry** [comment]
Thank you. Yes, I had started down the path of porting Assisticant to .NET Standard 2.0. I will take a look at your PR and see if that solves the problems that I was having. This is the first step toward Xamarin.Forms support.

**Comment by michaellperry** [comment]
The Android and iOS libraries now use the Netstandard 1.4 build, not PCL.
