### ISSUE TITLE
ObservableDictionary does not implement non-generic IDictionary interface.

### ISSUE THREAD

**Issue by russell-elledge** [michaellperry/Assisticant#36]
Assisticant's ObservableCollection<> class has base classes that support both System.Collections.Generic.ILIst and System.Collections.ILIst.

Assisticant's ObservableDictionary does not implement both System.Collections.Generic.IDictionary and System.Collections.IDictionary.  Only the former generic form is implemented.

This prevents ObservableDictionary from being passed to a utility method as an untyped System.Collections.IDictionary.  Instead, methods must know the fully typed signature of the incoming ObservableDictionary or IDictionary<TKey, TValue>.

**Comment by michaellperry** [comment]
Good call out. Would you be interested in creating a PR on that? Sounds like a good patch.

**Comment by russell-elledge** [comment]
...pull request submitted.

**Comment by michaellperry** [comment]
PR merged
